import { describe, expect, it } from "vitest";

import {
  createDesktopAuthCallbackUrl,
  createDesktopAuthDeepLink,
  desktopAuthCompleteSearchSchema,
  desktopAuthRequestSearchSchema,
} from "./desktop-auth-contracts";

const requestId = "r".repeat(43);
const authorizationCode = "A_-".repeat(14) + "A";

describe("desktop auth route contracts", () => {
  it("accepts the fixed-length base64url request generated by the desktop app", () => {
    expect(
      desktopAuthRequestSearchSchema.parse({ request_id: requestId }),
    ).toEqual({ request_id: requestId });
  });

  it("accepts only a fixed loopback callback URL", () => {
    const callbackUrl = "http://127.0.0.1:43123/auth/desktop-complete";
    expect(
      desktopAuthRequestSearchSchema.parse({
        callback_url: callbackUrl,
        request_id: requestId,
      }),
    ).toEqual({ callback_url: callbackUrl, request_id: requestId });

    for (const invalidCallback of [
      "https://127.0.0.1:43123/auth/desktop-complete",
      "http://localhost:43123/auth/desktop-complete",
      "http://127.0.0.1/auth/desktop-complete",
      "http://127.0.0.1:43123/other",
      "http://127.0.0.1:43123/auth/desktop-complete?extra=true",
    ]) {
      expect(
        desktopAuthRequestSearchSchema.safeParse({
          callback_url: invalidCallback,
          request_id: requestId,
        }).success,
      ).toBe(false);
    }
  });

  it.each([
    "short",
    "r".repeat(42),
    "r".repeat(44),
    `${"r".repeat(42)}+`,
    `${"r".repeat(42)}=`,
  ])("rejects an invalid desktop request token %s", (invalidToken) => {
    expect(
      desktopAuthRequestSearchSchema.safeParse({ request_id: invalidToken })
        .success,
    ).toBe(false);
  });

  it("requires both valid callback credentials", () => {
    expect(
      desktopAuthCompleteSearchSchema.safeParse({ request_id: requestId })
        .success,
    ).toBe(false);
    expect(
      desktopAuthCompleteSearchSchema.safeParse({
        authorization_code: authorizationCode,
        request_id: requestId,
      }).success,
    ).toBe(true);
  });

  it("encodes an approved callback as the canonical desktop deep link", () => {
    const deepLink = new URL(
      createDesktopAuthDeepLink(requestId, authorizationCode),
    );

    expect(`${deepLink.protocol}//${deepLink.host}${deepLink.pathname}`).toBe(
      "rodge-mail://auth/desktop-complete",
    );
    expect(deepLink.searchParams.get("request_id")).toBe(requestId);
    expect(deepLink.searchParams.get("authorization_code")).toBe(
      authorizationCode,
    );
  });

  it("encodes an approved callback for the native loopback listener", () => {
    const callback = new URL(
      createDesktopAuthCallbackUrl(
        "http://127.0.0.1:43123/auth/desktop-complete",
        requestId,
        authorizationCode,
      ),
    );

    expect(callback.origin).toBe("http://127.0.0.1:43123");
    expect(callback.pathname).toBe("/auth/desktop-complete");
    expect(callback.searchParams.get("request_id")).toBe(requestId);
    expect(callback.searchParams.get("authorization_code")).toBe(
      authorizationCode,
    );
  });
});
