import { describe, expect, it } from "vitest";

import {
  createDesktopAuthDeepLink,
  desktopAuthCompleteSearchSchema,
  desktopAuthRequestSearchSchema,
} from "./desktop-auth-contracts";

const requestId = "r".repeat(43);
const authorizationCode = "A_-".repeat(14) + "A";

describe("desktop auth route contracts", () => {
  it("accepts the fixed-length base64url request generated by the desktop app", () => {
    expect(
      desktopAuthRequestSearchSchema.parse({ request_id: requestId }),
    ).toEqual({ request_id: requestId });
  });

  it.each([
    "short",
    "r".repeat(42),
    "r".repeat(44),
    `${"r".repeat(42)}+`,
    `${"r".repeat(42)}=`,
  ])("rejects an invalid desktop request token %s", (invalidToken) => {
    expect(
      desktopAuthRequestSearchSchema.safeParse({ request_id: invalidToken })
        .success,
    ).toBe(false);
  });

  it("requires both valid callback credentials", () => {
    expect(
      desktopAuthCompleteSearchSchema.safeParse({ request_id: requestId })
        .success,
    ).toBe(false);
    expect(
      desktopAuthCompleteSearchSchema.safeParse({
        authorization_code: authorizationCode,
        request_id: requestId,
      }).success,
    ).toBe(true);
  });

  it("encodes an approved callback as the canonical desktop deep link", () => {
    const deepLink = new URL(
      createDesktopAuthDeepLink(requestId, authorizationCode),
    );

    expect(`${deepLink.protocol}//${deepLink.host}${deepLink.pathname}`).toBe(
      "rodge-mail://auth/desktop-complete",
    );
    expect(deepLink.searchParams.get("request_id")).toBe(requestId);
    expect(deepLink.searchParams.get("authorization_code")).toBe(
      authorizationCode,
    );
  });
});
