/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as DesktopAuthRouteImport } from './app/desktop-auth'
import { Route as AuthedRouteImport } from './app/_authed'
import { Route as AuthedIndexRouteImport } from './app/_authed/index'
import { Route as AuthDesktopCompleteRouteImport } from './app/auth.desktop-complete'
import { Route as AuthCallbackRouteImport } from './app/auth.callback'
import { Route as ApiAuthSplatRouteImport } from './app/api.auth.$'
import { Route as AuthedMessagesMessageIdRouteImport } from './app/_authed.messages.$messageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopAuthRoute = DesktopAuthRouteImport.update({
  id: '/desktop-auth',
  path: '/desktop-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthDesktopCompleteRoute = AuthDesktopCompleteRouteImport.update({
  id: '/auth/desktop-complete',
  path: '/auth/desktop-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMessagesMessageIdRoute = AuthedMessagesMessageIdRouteImport.update({
  id: '/messages/$messageId',
  path: '/messages/$messageId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/desktop-auth': typeof DesktopAuthRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop-complete': typeof AuthDesktopCompleteRoute
  '/messages/$messageId': typeof AuthedMessagesMessageIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/desktop-auth': typeof DesktopAuthRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop-complete': typeof AuthDesktopCompleteRoute
  '/': typeof AuthedIndexRoute
  '/messages/$messageId': typeof AuthedMessagesMessageIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/desktop-auth': typeof DesktopAuthRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/desktop-complete': typeof AuthDesktopCompleteRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/messages/$messageId': typeof AuthedMessagesMessageIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desktop-auth'
    | '/login'
    | '/auth/callback'
    | '/auth/desktop-complete'
    | '/messages/$messageId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/desktop-auth'
    | '/login'
    | '/auth/callback'
    | '/auth/desktop-complete'
    | '/'
    | '/messages/$messageId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/desktop-auth'
    | '/login'
    | '/auth/callback'
    | '/auth/desktop-complete'
    | '/_authed/'
    | '/_authed/messages/$messageId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  DesktopAuthRoute: typeof DesktopAuthRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDesktopCompleteRoute: typeof AuthDesktopCompleteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-auth': {
      id: '/desktop-auth'
      path: '/desktop-auth'
      fullPath: '/desktop-auth'
      preLoaderRoute: typeof DesktopAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/desktop-complete': {
      id: '/auth/desktop-complete'
      path: '/auth/desktop-complete'
      fullPath: '/auth/desktop-complete'
      preLoaderRoute: typeof AuthDesktopCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/messages/$messageId': {
      id: '/_authed/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof AuthedMessagesMessageIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedMessagesMessageIdRoute: typeof AuthedMessagesMessageIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedMessagesMessageIdRoute: AuthedMessagesMessageIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  DesktopAuthRoute: DesktopAuthRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDesktopCompleteRoute: AuthDesktopCompleteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
